import { internalMutation } from './_generated/server'

// Seed the catalog. Run with: `npx convex run seed:run`
// Idempotent: no-op if subjects already exist. To re-apply after taxonomy
// changes, run `npx convex run seed:reset` first (see below), then re-run.
export const run = internalMutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query('subjects').collect()
    if (existing.length > 0) return 'already seeded'

    const subjectsData = [
      {
        slug: 'physics',
        name: 'Physics',
        description: 'See the rules of the universe in motion.',
        color: '#6C5CE7',
        icon: 'Atom',
        order: 1,
        isPublished: true,
      },
      {
        slug: 'chemistry',
        name: 'Chemistry',
        description: 'Build the world one reaction at a time.',
        color: '#00D2D3',
        icon: 'FlaskConical',
        order: 2,
        isPublished: false,
      },
      {
        slug: 'biology',
        name: 'Biology',
        description: 'Explore the machinery of life.',
        color: '#2ECC71',
        icon: 'Dna',
        order: 3,
        isPublished: false,
      },
      {
        slug: 'math',
        name: 'Math',
        description: 'The language behind everything.',
        color: '#FFB020',
        icon: 'Sigma',
        order: 4,
        isPublished: false,
      },
      {
        slug: 'computer-science',
        name: 'Computer Science',
        description: 'Teach a machine to think.',
        color: '#FF6B6B',
        icon: 'Binary',
        order: 5,
        isPublished: false,
      },
      {
        slug: 'psychology',
        name: 'Psychology',
        description: 'Decode the human mind.',
        color: '#E056FD',
        icon: 'Brain',
        order: 6,
        isPublished: false,
      },
    ]

    const subjectIds: Record<string, any> = {}
    for (const s of subjectsData) {
      subjectIds[s.slug] = await ctx.db.insert('subjects', s)
    }

    // The ~12 Physics domain categories ("units"). Each is a navigable category
    // with its own table of contents and blends Beginner -> Advanced internally.
    const unitsData: Array<{
      slug: string
      name: string
      order: number
      description: string
      icon: string
      accentColor: string
      levelRange: string
    }> = [
      {
        slug: 'scientific-working',
        name: 'Scientific Working & Measurement',
        order: 1,
        description: 'How science actually works: method, units, and data.',
        icon: 'Microscope',
        accentColor: '#00B894',
        levelRange: 'Beginner',
      },
      {
        slug: 'energy',
        name: 'Energy & Work',
        order: 2,
        description: 'The currency of change — stored, transferred, conserved.',
        icon: 'Zap',
        accentColor: '#FDCB6E',
        levelRange: 'Beginner → Intermediate',
      },
      {
        slug: 'forces-and-motion',
        name: 'Forces & Motion',
        order: 3,
        description: "From everyday pushes to Newton's laws and orbits.",
        icon: 'Move',
        accentColor: '#6C5CE7',
        levelRange: 'Beginner → Advanced',
      },
      {
        slug: 'oscillations',
        name: 'Oscillations & Waves',
        order: 4,
        description: 'Rhythms, ripples, and the physics of vibration.',
        icon: 'Waves',
        accentColor: '#00CEC9',
        levelRange: 'Beginner → Advanced',
      },
      {
        slug: 'light-and-optics',
        name: 'Light & Optics',
        order: 5,
        description: 'How light travels, bends, and lets us see.',
        icon: 'Sun',
        accentColor: '#FAB1A0',
        levelRange: 'Beginner → Advanced',
      },
      {
        slug: 'electricity',
        name: 'Electricity & Circuits',
        order: 6,
        description: 'Charge in motion, from sparks to circuits.',
        icon: 'CircuitBoard',
        accentColor: '#E17055',
        levelRange: 'Beginner → Advanced',
      },
      {
        slug: 'magnetism',
        name: 'Magnetism & Electromagnetism',
        order: 7,
        description: 'Magnets, fields, and the link between them and electricity.',
        icon: 'Magnet',
        accentColor: '#D63031',
        levelRange: 'Intermediate → Advanced',
      },
      {
        slug: 'matter',
        name: 'Matter, Pressure & Heat',
        order: 8,
        description: 'States of matter, density, pressure, and thermal energy.',
        icon: 'Thermometer',
        accentColor: '#0984E3',
        levelRange: 'Beginner → Advanced',
      },
      {
        slug: 'atoms-and-quantum',
        name: 'Atoms, Radioactivity & Quantum',
        order: 9,
        description: 'Inside the atom — and the strange rules it obeys.',
        icon: 'Atom',
        accentColor: '#A29BFE',
        levelRange: 'Intermediate → Advanced',
      },
      {
        slug: 'relativity',
        name: 'Relativity',
        order: 10,
        description: 'How space, time, and gravity bend.',
        icon: 'Orbit',
        accentColor: '#74B9FF',
        levelRange: 'Advanced',
      },
      {
        slug: 'astronomy',
        name: 'Astronomy & Cosmology',
        order: 11,
        description: 'Stars, galaxies, and the story of the universe.',
        icon: 'Telescope',
        accentColor: '#4834D4',
        levelRange: 'Beginner → Advanced',
      },
      {
        slug: 'frontiers',
        name: 'Frontiers & Special Topics',
        order: 12,
        description: 'Crystals, geophysics, and the edge of what we know.',
        icon: 'Sparkles',
        accentColor: '#E84393',
        levelRange: 'Advanced',
      },
    ]

    const unitIds: Record<string, any> = {}
    for (const u of unitsData) {
      unitIds[u.slug] = await ctx.db.insert('units', {
        subjectId: subjectIds['physics'],
        slug: u.slug,
        name: u.name,
        order: u.order,
        description: u.description,
        icon: u.icon,
        accentColor: u.accentColor,
        levelRange: u.levelRange,
      })
    }

    // Lessons. `isPublished: true` lessons have authored MDX (matched by
    // contentSlug in src/lib/lessonModules.ts); unpublished rows are the visible
    // roadmap shown as "coming soon" nodes in the category table of contents.
    const lessonsData: Array<{
      unitSlug: string
      contentSlug: string
      title: string
      summary: string
      order: number
      estimatedMinutes: number
      xpReward: number
      isPublished: boolean
      level: 'beginner' | 'intermediate' | 'advanced'
      format: 'core' | 'deepdive'
    }> = [
      // --- Oscillations & Waves (third fully-mapped category) ---
      {
        unitSlug: 'oscillations',
        contentSlug: 'physics/simple-harmonic-motion',
        title: 'Why a Pendulum Swings',
        summary: 'Discover what really controls the rhythm of a pendulum.',
        order: 1,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'oscillations',
        contentSlug: 'physics/frequency-and-period',
        title: 'Frequency & Period',
        summary: 'The two numbers that describe any rhythm — and why they’re reciprocals.',
        order: 2,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'oscillations',
        contentSlug: 'physics/waves-and-wavelength',
        title: 'Waves & Wavelength',
        summary: 'How energy travels without matter — and the anatomy of a wave.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'oscillations',
        contentSlug: 'physics/wave-speed',
        title: 'Wave Speed (v = fλ)',
        summary: 'The one equation linking frequency, wavelength, and speed.',
        order: 4,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'oscillations',
        contentSlug: 'physics/sound',
        title: 'Sound',
        summary: 'Pressure waves in air: pitch, loudness, and why space is silent.',
        order: 5,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'oscillations',
        contentSlug: 'physics/reflection-and-refraction',
        title: 'Reflection & Refraction',
        summary: 'How waves bounce off and bend through boundaries.',
        order: 6,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'oscillations',
        contentSlug: 'physics/interference-and-standing-waves',
        title: 'Interference & Standing Waves',
        summary: 'Superposition, beats, and the standing waves that make music.',
        order: 7,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Light & Optics (fourth fully-mapped category) ---
      {
        unitSlug: 'light-and-optics',
        contentSlug: 'physics/what-is-light',
        title: 'What Is Light?',
        summary: 'Straight-line rays, shadows, and the fastest thing there is.',
        order: 1,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'light-and-optics',
        contentSlug: 'physics/reflection-and-mirrors',
        title: 'Reflection & Mirrors',
        summary: 'The law of reflection and how mirrors form images.',
        order: 2,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'light-and-optics',
        contentSlug: 'physics/refraction-bending-light',
        title: 'Refraction — Bending Light',
        summary: 'Why light bends, refractive index, and total internal reflection.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'light-and-optics',
        contentSlug: 'physics/lenses-and-images',
        title: 'Lenses & Images',
        summary: 'Converging and diverging lenses, focal points, and the eye.',
        order: 4,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'light-and-optics',
        contentSlug: 'physics/color-and-dispersion',
        title: 'Color & Dispersion',
        summary: 'White light, prisms, rainbows, and why objects have colour.',
        order: 5,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'light-and-optics',
        contentSlug: 'physics/the-electromagnetic-spectrum',
        title: 'The Electromagnetic Spectrum',
        summary: 'Radio to gamma: one family of waves, ranked by energy.',
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'light-and-optics',
        contentSlug: 'physics/wave-optics',
        title: 'Wave Optics: Diffraction & Interference',
        summary: 'Diffraction, the double slit, and the proof that light is a wave.',
        order: 7,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Matter, Pressure & Heat (fifth fully-mapped category) ---
      {
        unitSlug: 'matter',
        contentSlug: 'physics/states-of-matter',
        title: 'States of Matter',
        summary: "Solid, liquid, gas — and why the only thing that changes is the particles' energy.",
        order: 1,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'matter',
        contentSlug: 'physics/density',
        title: 'Density',
        summary: 'Mass packed into volume — what makes things float, sink, or fly.',
        order: 2,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'matter',
        contentSlug: 'physics/pressure',
        title: 'Pressure',
        summary: "Force focused onto an area — why sharp things pierce and snowshoes don't sink.",
        order: 3,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'matter',
        contentSlug: 'physics/pressure-in-fluids',
        title: 'Pressure in Fluids',
        summary: 'Why pressure grows with depth, holds up an ocean of air, and powers hydraulics.',
        order: 4,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'matter',
        contentSlug: 'physics/gas-laws',
        title: 'The Gas Laws',
        summary: 'Boyle, Charles, and Gay-Lussac — how a gas trades pressure, volume, and temperature.',
        order: 5,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'matter',
        contentSlug: 'physics/heat-transfer',
        title: 'Heat Transfer',
        summary: 'Conduction, convection, and radiation — the three routes heat takes.',
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'matter',
        contentSlug: 'physics/changes-of-state',
        title: 'Changes of State & Latent Heat',
        summary: "Melting and boiling, and the hidden 'latent' heat they swallow.",
        order: 7,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'matter',
        contentSlug: 'physics/kinetic-theory-of-gases',
        title: 'The Kinetic Theory of Gases',
        summary: 'One picture of bouncing particles that explains pressure, temperature, and every gas law.',
        order: 8,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Electricity & Circuits (sixth fully-mapped category) ---
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/static-electricity',
        title: 'Static Electricity',
        summary: 'Charge at rest — why balloons stick, combs lift paper, and clouds throw lightning.',
        order: 1,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/electric-current',
        title: 'Electric Current',
        summary: 'Charge set in motion — what an amp really counts.',
        order: 2,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/voltage',
        title: 'Voltage',
        summary: 'The push that drives a circuit — energy handed to every charge.',
        order: 3,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/resistance',
        title: 'Resistance',
        summary: 'The circuit pushing back — opposition that turns into heat and light.',
        order: 4,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/ohms-law',
        title: "Ohm's Law",
        summary: 'V = I × R — the one equation that ties a circuit together.',
        order: 5,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/series-and-parallel-circuits',
        title: 'Series & Parallel Circuits',
        summary: 'One loop or many — and why your home is wired in parallel.',
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/electrical-power',
        title: 'Electrical Power & Energy',
        summary: 'Watts, heating wires, and what your electricity bill actually charges for.',
        order: 7,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'electricity',
        contentSlug: 'physics/how-circuits-work',
        title: 'How a Circuit Really Works',
        summary: 'Why the light comes on instantly when the electrons barely move.',
        order: 8,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Magnetism & Electromagnetism (seventh fully-mapped category) ---
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/magnets-and-fields',
        title: 'Magnets & Magnetic Fields',
        summary: 'Poles, fields, and why you can never cut a magnet down to a single pole.',
        order: 1,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/electromagnetism',
        title: 'Electric Currents Make Magnetism',
        summary: "Ørsted's accident: a current wraps the space around it in a magnetic field.",
        order: 2,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/electromagnets',
        title: 'Electromagnets',
        summary: 'Coil a wire and build a magnet you can switch, strengthen, and reverse.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/motor-effect',
        title: 'The Motor Effect',
        summary: 'A current in a field feels a force — the push behind every electric motor.',
        order: 4,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/electromagnetic-induction',
        title: 'Electromagnetic Induction',
        summary: 'A changing magnetic field makes electricity — Faraday and Lenz.',
        order: 5,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/generators',
        title: 'Generators',
        summary: 'Spin a coil in a field and turn motion into the AC that powers the world.',
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/transformers',
        title: 'Transformers & the Grid',
        summary: 'Step voltage up and down with the turns ratio — why the grid runs on AC.',
        order: 7,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'magnetism',
        contentSlug: 'physics/maxwell-and-em-waves',
        title: "Maxwell's Unification & Electromagnetic Waves",
        summary: 'How electricity + magnetism became one — and revealed that light is a wave.',
        order: 8,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Atoms, Radioactivity & Quantum (eighth fully-mapped category) ---
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/inside-the-atom',
        title: 'Inside the Atom',
        summary: 'Protons, neutrons, electrons — and the mostly-empty space they leave behind.',
        order: 1,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/isotopes',
        title: 'Isotopes & Atomic Mass',
        summary: 'Same element, different neutron count — and why periodic-table masses aren’t whole numbers.',
        order: 2,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/radioactivity',
        title: 'What Is Radioactivity?',
        summary: 'Unstable nuclei and the three radiations — alpha, beta, gamma.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/radioactive-decay',
        title: 'Radioactive Decay & Half-Life',
        summary: 'Random decay, the half-life rule, and how it dates the past.',
        order: 4,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/nuclear-energy',
        title: 'Nuclear Energy: Fission & Fusion',
        summary: 'E = mc², splitting heavy nuclei, and fusing the light ones that power the stars.',
        order: 5,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/quantum-leap',
        title: 'The Quantum Leap: Light as Particles',
        summary: 'Photons, the photoelectric effect, and the experiment that broke classical physics.',
        order: 6,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/wave-particle-duality',
        title: 'Wave–Particle Duality & the Atom',
        summary: 'Matter as waves, standing-wave orbits, and the spectral fingerprints of atoms.',
        order: 7,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'atoms-and-quantum',
        contentSlug: 'physics/quantum-world',
        title: 'Into the Quantum World',
        summary: 'Superposition, probability clouds, uncertainty, tunnelling — the rules that run reality.',
        order: 8,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Relativity (ninth fully-mapped category) ---
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/relativity-postulates',
        title: 'The Speed of Light Is Absolute',
        summary: 'Why c is the same for everyone — and the two postulates that rebuilt physics.',
        order: 1,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/time-dilation',
        title: 'Time Dilation',
        summary: 'A light clock shows why moving clocks genuinely run slow.',
        order: 2,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/length-contraction',
        title: 'Length Contraction',
        summary: 'Moving objects shrink along their motion — by the same factor that slows time.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/relativity-of-simultaneity',
        title: 'The Relativity of Simultaneity',
        summary: 'Whether two events happen “at once” depends on how you’re moving.',
        order: 4,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/mass-energy',
        title: 'E = mc² and the Cosmic Speed Limit',
        summary: 'Why nothing with mass reaches c — and how mass itself is frozen energy.',
        order: 5,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/equivalence-principle',
        title: 'The Equivalence Principle',
        summary: "Einstein's happiest thought: gravity and acceleration are indistinguishable.",
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/curved-spacetime',
        title: 'Curved Spacetime',
        summary: 'Gravity isn’t a force — it’s the curvature of spacetime, and orbits are straight lines through it.',
        order: 7,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'relativity',
        contentSlug: 'physics/black-holes-and-cosmos',
        title: 'Black Holes & the Shape of the Cosmos',
        summary: 'Event horizons, gravitational waves, the expanding universe, and the frontier with the quantum.',
        order: 8,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Astronomy & Cosmology (tenth fully-mapped category) ---
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/the-moving-sky',
        title: 'The Moving Sky',
        summary: 'Day, night, the year, and why the tilt — not distance — makes the seasons.',
        order: 1,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/moon-and-eclipses',
        title: 'The Moon & Eclipses',
        summary: 'Phases, solar and lunar eclipses, and the tides the Moon raises.',
        order: 2,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/the-solar-system',
        title: 'The Solar System',
        summary: 'The Sun’s family — orbits, Kepler’s law, two kinds of planets, and the icy edge.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/life-of-a-star',
        title: 'The Life of a Star',
        summary: 'Birth in a nebula, fusion, and a fate set by mass — white dwarf, neutron star, or black hole.',
        order: 4,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/measuring-the-universe',
        title: 'Measuring the Universe',
        summary: 'Parallax, standard candles, and why looking far is looking back in time.',
        order: 5,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/galaxies-and-cosmic-scale',
        title: 'Galaxies & the Cosmic Scale',
        summary: 'The Milky Way, the zoo of galaxies, and the cosmic web that spans the universe.',
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/the-expanding-universe',
        title: 'The Expanding Universe',
        summary: 'Redshift, Hubble’s law, and the stretching of space that points back to the Big Bang.',
        order: 7,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'astronomy',
        contentSlug: 'physics/big-bang-and-fate',
        title: 'The Big Bang & the Fate of the Universe',
        summary: 'Cosmic history, the microwave background, dark matter and energy, and how it might all end.',
        order: 8,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Energy & Work (second fully-mapped category) ---
      {
        unitSlug: 'energy',
        contentSlug: 'physics/what-is-energy',
        title: 'What Is Energy?',
        summary: 'The currency every change is paid in — and its many forms.',
        order: 1,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'energy',
        contentSlug: 'physics/kinetic-and-potential-energy',
        title: 'Kinetic & Potential Energy',
        summary: 'Energy of motion and energy of position, forever trading places.',
        order: 2,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'energy',
        contentSlug: 'physics/conservation-of-energy',
        title: 'Conservation of Energy',
        summary: "Physics' unbreakable accounting rule: energy is never lost.",
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'energy',
        contentSlug: 'physics/work-force-and-distance',
        title: 'Work = Force × Distance',
        summary: 'How a force moving through a distance transfers energy.',
        order: 4,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'energy',
        contentSlug: 'physics/power',
        title: 'Power',
        summary: 'The rate of doing work — energy spent per second.',
        order: 5,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'energy',
        contentSlug: 'physics/energy-transfer-and-efficiency',
        title: 'Energy Transfer & Efficiency',
        summary: 'Why every machine wastes some energy as heat.',
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'energy',
        contentSlug: 'physics/heat-and-temperature',
        title: 'Heat & Temperature',
        summary: 'Jiggling particles, and the difference between hot and heat.',
        order: 7,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'energy',
        contentSlug: 'physics/entropy-and-the-second-law',
        title: 'Entropy & the Second Law',
        summary: 'Disorder, the arrow of time, and the deepest rule in physics.',
        order: 8,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Forces & Motion (first fully-mapped category) ---
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/what-is-motion',
        title: 'What Is Motion?',
        summary: 'Position, distance, and how we describe where things go.',
        order: 1,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/speed-and-velocity',
        title: 'Speed & Velocity',
        summary: 'How fast — and how fast in a direction.',
        order: 2,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/motion-graphs',
        title: 'Reading Motion Graphs',
        summary: 'Turn position- and velocity-time graphs into intuition.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/acceleration',
        title: 'Acceleration',
        summary: 'What it means to speed up, slow down, or change direction.',
        order: 4,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/forces-pushes-and-pulls',
        title: 'Forces: Pushes & Pulls',
        summary: 'Forces as vectors — how they add up and cancel out.',
        order: 5,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/newtons-first-law',
        title: "Newton's First Law (Inertia)",
        summary: 'Why things keep doing what they’re doing.',
        order: 6,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/newtons-second-law',
        title: "Newton's Second Law (F = ma)",
        summary: 'The exact link between force, mass, and acceleration.',
        order: 7,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/newtons-third-law',
        title: "Newton's Third Law",
        summary: 'Every action has an equal and opposite reaction.',
        order: 8,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/friction',
        title: 'Friction',
        summary: 'The hidden force that resists motion.',
        order: 9,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/gravity-and-free-fall',
        title: 'Gravity & Free Fall',
        summary: 'Why everything falls at the same rate (ignoring air).',
        order: 10,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/projectile-motion',
        title: 'Projectile Motion',
        summary: 'Split motion into horizontal + vertical to predict the arc.',
        order: 11,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'intermediate',
        format: 'deepdive',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/momentum-and-collisions',
        title: 'Momentum & Collisions',
        summary: 'The conserved quantity behind crashes, recoil, and rockets.',
        order: 12,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/circular-motion',
        title: 'Circular Motion',
        summary: 'Why turning needs a center-pointing force.',
        order: 13,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'forces-and-motion',
        contentSlug: 'physics/orbits-and-gravitation',
        title: 'Orbits & Universal Gravitation',
        summary: 'How the gravity that drops an apple holds the Moon in orbit.',
        order: 14,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Scientific Working & Measurement (eleventh fully-mapped category, order 1) ---
      {
        unitSlug: 'scientific-working',
        contentSlug: 'physics/what-is-physics',
        title: 'What Is Physics?',
        summary: 'The search for the universe’s rules — and the scientific method that finds them.',
        order: 1,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'scientific-working',
        contentSlug: 'physics/measuring-the-world',
        title: 'Measuring the World',
        summary: 'The seven SI base units every other measurement is built from.',
        order: 2,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'scientific-working',
        contentSlug: 'physics/powers-of-ten',
        title: 'Powers of Ten',
        summary: 'Scientific notation and orders of magnitude — taming atoms to galaxies.',
        order: 3,
        estimatedMinutes: 6,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'scientific-working',
        contentSlug: 'physics/units-and-conversion',
        title: 'Units, Prefixes & Conversion',
        summary: 'Prefixes, converting units by multiplying by one, and letting units check your work.',
        order: 4,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'beginner',
        format: 'core',
      },
      {
        unitSlug: 'scientific-working',
        contentSlug: 'physics/precision-and-uncertainty',
        title: 'Precision & Uncertainty',
        summary: 'Why no measurement is exact — accuracy vs precision, random vs systematic error.',
        order: 5,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'scientific-working',
        contentSlug: 'physics/graphs-and-relationships',
        title: 'Graphs & Relationships',
        summary: 'Reading the law out of the data — slopes, proportionality, and the line of best fit.',
        order: 6,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'scientific-working',
        contentSlug: 'physics/from-data-to-laws',
        title: 'From Data to Laws',
        summary: 'How science turns measurements into universal laws — and how it self-corrects.',
        order: 7,
        estimatedMinutes: 12,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },

      // --- Frontiers & Special Topics (twelfth fully-mapped category, order 12) ---
      {
        unitSlug: 'frontiers',
        contentSlug: 'physics/crystals-and-solids',
        title: 'The Crystalline World',
        summary: 'Long-range order, lattices, defects, and how X-rays read the atoms inside a solid.',
        order: 1,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'frontiers',
        contentSlug: 'physics/semiconductors',
        title: 'Semiconductors: The Physics of the Chip',
        summary: 'Energy bands, the band gap, doping, and the transistor behind all electronics.',
        order: 2,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'frontiers',
        contentSlug: 'physics/superconductivity',
        title: 'Superconductivity',
        summary: 'Zero resistance, magnetic levitation, Cooper pairs, and the room-temperature dream.',
        order: 3,
        estimatedMinutes: 7,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'frontiers',
        contentSlug: 'physics/inside-the-earth',
        title: 'Inside the Earth',
        summary: 'How seismic waves reveal a layered planet — and a liquid core that shields us.',
        order: 4,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'intermediate',
        format: 'core',
      },
      {
        unitSlug: 'frontiers',
        contentSlug: 'physics/chaos-and-complexity',
        title: 'Chaos & the Butterfly Effect',
        summary: 'Deterministic yet unpredictable — sensitivity to initial conditions and why weather defies forecasting.',
        order: 5,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'frontiers',
        contentSlug: 'physics/standard-model',
        title: 'The Particle Zoo & the Standard Model',
        summary: 'Quarks, leptons, the force-carrying bosons, and the Higgs — the full inventory of matter.',
        order: 6,
        estimatedMinutes: 8,
        xpReward: 50,
        isPublished: true,
        level: 'advanced',
        format: 'core',
      },
      {
        unitSlug: 'frontiers',
        contentSlug: 'physics/edge-of-physics',
        title: 'The Edge of the Known',
        summary: 'Dark matter, dark energy, quantum gravity, and the great open questions at physics’ frontier.',
        order: 7,
        estimatedMinutes: 13,
        xpReward: 100,
        isPublished: true,
        level: 'advanced',
        format: 'deepdive',
      },
    ]

    for (const l of lessonsData) {
      await ctx.db.insert('lessons', {
        subjectId: subjectIds['physics'],
        unitId: unitIds[l.unitSlug],
        contentSlug: l.contentSlug,
        title: l.title,
        summary: l.summary,
        order: l.order,
        estimatedMinutes: l.estimatedMinutes,
        xpReward: l.xpReward,
        isPublished: l.isPublished,
        level: l.level,
        format: l.format,
      })
    }

    return 'seeded'
  },
})

// Wipe the catalog so `run` can re-seed an updated taxonomy. Dev-only.
// Run with: `npx convex run seed:reset`. Leaves users/userProgress intact;
// any progress pointing at deleted lessons simply stops matching (harmless).
export const reset = internalMutation({
  args: {},
  handler: async (ctx) => {
    for (const table of ['lessons', 'units', 'subjects'] as const) {
      const docs = await ctx.db.query(table).collect()
      for (const d of docs) await ctx.db.delete(d._id)
    }
    return 'reset'
  },
})
