// AUTO-GENERATED by scripts/extract-practice-items.mjs — do not edit by hand.
// Source of truth: the <Quiz> in each lesson MDX. Re-run after editing quizzes:
//   node scripts/extract-practice-items.mjs
import type { PracticeItem } from '#/lib/practice'

export const PRACTICE_BANK: Array<PracticeItem> = [
  {
    "id": "physics/acceleration",
    "contentSlug": "physics/acceleration",
    "subject": "physics",
    "lessonTitle": "Acceleration",
    "prompt": "A car speeds up from 0 to 20 m/s in 4 seconds. What is its acceleration?",
    "options": [
      "5 m/s²",
      "80 m/s²",
      "16 m/s²",
      "4 m/s²"
    ],
    "correctIndex": 0,
    "explanation": "a = Δv / Δt = (20 − 0) m/s ÷ 4 s = 5 m/s². The car gains 5 m/s of speed every second."
  },
  {
    "id": "physics/big-bang-and-fate",
    "contentSlug": "physics/big-bang-and-fate",
    "subject": "physics",
    "lessonTitle": "The Big Bang & the Fate of the Universe",
    "prompt": "The cosmic microwave background (CMB) is best described as:",
    "options": [
      "Light from the first galaxies forming",
      "The stretched-out afterglow of the hot early universe, released when atoms first formed ~380,000 years after the Big Bang",
      "Radiation produced by the Sun",
      "The glow of dark matter"
    ],
    "correctIndex": 1,
    "explanation": "The CMB is relic light from when the universe cooled enough (~380,000 years in) for atoms to form and light to travel freely. Stretched by 13.8 billion years of expansion into faint microwaves at ~2.7 K, it fills the whole sky and is the strongest evidence for the Big Bang."
  },
  {
    "id": "physics/black-holes-and-cosmos",
    "contentSlug": "physics/black-holes-and-cosmos",
    "subject": "physics",
    "lessonTitle": "Black Holes & the Shape of the Cosmos",
    "prompt": "What is the event horizon of a black hole?",
    "options": [
      "The solid surface of the black hole",
      "The boundary beyond which escape would require exceeding the speed of light, so nothing — not even light — can get out",
      "The point where the black hole stops growing",
      "A ring of light that orbits forever without falling in"
    ],
    "correctIndex": 1,
    "explanation": "The event horizon is the boundary where spacetime curvature is so extreme that the escape velocity equals the speed of light. Since nothing can travel faster than light, anything crossing the horizon — matter, light, information — can never return. The true centre holds the singularity, where general relativity breaks down."
  },
  {
    "id": "physics/changes-of-state",
    "contentSlug": "physics/changes-of-state",
    "subject": "physics",
    "lessonTitle": "Changes of State & Latent Heat",
    "prompt": "While ice is melting, you keep adding heat but the temperature stays at 0 °C. Where is the energy going?",
    "options": [
      "It's being destroyed",
      "Into breaking the bonds of the solid structure — the latent heat of melting",
      "Into making the ice colder",
      "Nowhere; the heat stops flowing"
    ],
    "correctIndex": 1,
    "explanation": "During a change of state the added energy goes into breaking the bonds holding particles in place (latent heat), not into raising their speed. Temperature — the measure of particle speed — therefore stays constant until the change is complete."
  },
  {
    "id": "physics/chaos-and-complexity",
    "contentSlug": "physics/chaos-and-complexity",
    "subject": "physics",
    "lessonTitle": "Chaos & the Butterfly Effect",
    "prompt": "A system is described as 'chaotic.' What does that most precisely mean?",
    "options": [
      "Its behaviour is random, governed by no laws",
      "It follows deterministic laws but is extremely sensitive to its initial conditions",
      "It always settles into a steady, repeating cycle",
      "It can only be described by quantum mechanics"
    ],
    "correctIndex": 1,
    "explanation": "Chaos is deterministic, not random — the laws fix the future exactly. But a vanishingly small change in the starting point grows exponentially, so any real (finite-precision) measurement makes long-term prediction impossible. That sensitivity is the defining feature."
  },
  {
    "id": "physics/circular-motion",
    "contentSlug": "physics/circular-motion",
    "subject": "physics",
    "lessonTitle": "Circular Motion",
    "prompt": "A ball whirls in a horizontal circle on a string. Which way does the net force on it point?",
    "options": [
      "Outward, away from the center",
      "Toward the center",
      "Forward, along its motion",
      "There is no net force"
    ],
    "correctIndex": 1,
    "explanation": "Circular motion requires a centripetal (center-pointing) net force — here, the string's tension. It bends the path without changing the speed."
  },
  {
    "id": "physics/color-and-dispersion",
    "contentSlug": "physics/color-and-dispersion",
    "subject": "physics",
    "lessonTitle": "Color & Dispersion",
    "prompt": "Under a pure green light, a red apple appears nearly black. Why?",
    "options": [
      "Green light destroys red objects",
      "The apple reflects only red light, and there's no red in the lamp to reflect",
      "Apples are actually black",
      "Green and red cancel out"
    ],
    "correctIndex": 1,
    "explanation": "An object's colour is the light it reflects. A red apple reflects red and absorbs the rest — so lit by only green light, it has nothing to reflect and looks black."
  },
  {
    "id": "physics/conservation-of-energy",
    "contentSlug": "physics/conservation-of-energy",
    "subject": "physics",
    "lessonTitle": "Conservation of Energy",
    "prompt": "A bouncing ball returns to a lower height after each bounce. Where did the 'missing' energy go?",
    "options": [
      "It was destroyed on impact",
      "It turned into heat and sound during each bounce",
      "Energy conservation simply fails for bouncing",
      "It was never there to begin with"
    ],
    "correctIndex": 1,
    "explanation": "Each bounce converts some mechanical energy into heat (the ball and floor warm slightly) and sound. Total energy is still conserved — it's just spread into harder-to-see forms."
  },
  {
    "id": "physics/crystals-and-solids",
    "contentSlug": "physics/crystals-and-solids",
    "subject": "physics",
    "lessonTitle": "The Crystalline World",
    "prompt": "Diamond and graphite are both made of pure carbon, yet one is the hardest natural material and the other is soft enough to write with. Why?",
    "options": [
      "They contain different isotopes of carbon",
      "The carbon atoms are arranged in different crystal lattices",
      "Graphite is actually a glass with no structure",
      "Diamond has more carbon atoms per atom"
    ],
    "correctIndex": 1,
    "explanation": "Identical atoms, different lattice. Diamond bonds carbon into a rigid 3-D tetrahedral network; graphite stacks it in flat sheets that slide over each other. The arrangement, not the ingredient, sets the properties."
  },
  {
    "id": "physics/curved-spacetime",
    "contentSlug": "physics/curved-spacetime",
    "subject": "physics",
    "lessonTitle": "Curved Spacetime",
    "prompt": "In general relativity, why does the Earth orbit the Sun?",
    "options": [
      "The Sun exerts an invisible pulling force across empty space",
      "The Sun curves the spacetime around it, and the Earth follows the straightest path through that curved geometry",
      "The Earth is constantly falling but keeps missing the Sun by luck",
      "Sunlight pushes the Earth in a circle"
    ],
    "correctIndex": 1,
    "explanation": "General relativity replaces the gravitational 'force' with geometry. The Sun's mass warps spacetime, and the Earth simply coasts along a geodesic — the straightest available path — through that warp. The orbit only looks curved because the spacetime it threads is curved."
  },
  {
    "id": "physics/density",
    "contentSlug": "physics/density",
    "subject": "physics",
    "lessonTitle": "Density",
    "prompt": "A solid steel ball sinks, but a steel ship floats. What's the key difference?",
    "options": [
      "The ship is made of lighter steel",
      "The ship's hollow, air-filled shape lowers its average density below water's",
      "Ships are pushed up by the wind",
      "Steel changes density when shaped into a ship"
    ],
    "correctIndex": 1,
    "explanation": "The material is identical. By enclosing a large volume of air, the ship's average density drops below that of water, so it displaces enough water to float. A solid ball has nowhere near enough volume to do that."
  },
  {
    "id": "physics/edge-of-physics",
    "contentSlug": "physics/edge-of-physics",
    "subject": "physics",
    "lessonTitle": "The Edge of the Known",
    "prompt": "Roughly what fraction of the universe is made of the ordinary matter described by the Standard Model — and why is the rest such a deep problem?",
    "options": [
      "About 95%; the missing 5% is just gas we haven't counted",
      "About 5%; the other ~95% is dark matter and dark energy, made of nothing we understand",
      "100%; there is no missing matter or energy",
      "About 50%; the rest is antimatter"
    ],
    "correctIndex": 1,
    "explanation": "Everything the Standard Model describes — all atoms, stars, and galaxies — is only ~5% of the universe. About 27% is unidentified dark matter and ~68% is dark energy. We detect both only through gravity and cosmic expansion; their true nature is unknown, making them among physics' biggest open problems."
  },
  {
    "id": "physics/electric-current",
    "contentSlug": "physics/electric-current",
    "subject": "physics",
    "lessonTitle": "Electric Current",
    "prompt": "An ammeter reads 2 A in a wire. What does that actually tell you?",
    "options": [
      "2 volts of charge are stored in the wire",
      "2 coulombs of charge flow past each second",
      "The wire has 2 ohms of resistance",
      "2 electrons pass per second"
    ],
    "correctIndex": 1,
    "explanation": "Current is the rate of charge flow: 1 amp = 1 coulomb per second, so 2 A means 2 coulombs of charge stream past each second (around 1.2 × 10¹⁹ electrons every second)."
  },
  {
    "id": "physics/electrical-power",
    "contentSlug": "physics/electrical-power",
    "subject": "physics",
    "lessonTitle": "Electrical Power & Energy",
    "prompt": "A device runs at 3 A from a 12 V supply. What is its power?",
    "options": [
      "4 W",
      "15 W",
      "36 W",
      "0.25 W"
    ],
    "correctIndex": 2,
    "explanation": "Power = voltage × current = 12 V × 3 A = 36 W. The device converts 36 joules of electrical energy every second."
  },
  {
    "id": "physics/electromagnetic-induction",
    "contentSlug": "physics/electromagnetic-induction",
    "subject": "physics",
    "lessonTitle": "Electromagnetic Induction",
    "prompt": "A bar magnet is held perfectly still inside a coil. What current is induced?",
    "options": [
      "A large steady current",
      "A current that slowly fades",
      "No current at all",
      "A current only if the magnet is strong enough"
    ],
    "correctIndex": 2,
    "explanation": "Induction depends on a *changing* magnetic field. A stationary magnet — no matter how strong, or how deep inside the coil — produces no change in flux, so no current is induced. Only motion (or some other change) drives a current."
  },
  {
    "id": "physics/electromagnetism",
    "contentSlug": "physics/electromagnetism",
    "subject": "physics",
    "lessonTitle": "Electric Currents Make Magnetism",
    "prompt": "A compass is placed beside a wire. It only deflects when the current is switched on. What does this show?",
    "options": [
      "The wire is a permanent magnet",
      "An electric current produces a magnetic field around the wire",
      "The compass is broken",
      "Electricity and magnetism are unrelated"
    ],
    "correctIndex": 1,
    "explanation": "This is exactly Ørsted's 1820 observation. The needle responds only while current flows, showing the current itself generates a magnetic field that wraps around the wire — the first evidence linking electricity and magnetism."
  },
  {
    "id": "physics/electromagnets",
    "contentSlug": "physics/electromagnets",
    "subject": "physics",
    "lessonTitle": "Electromagnets",
    "prompt": "What is the single biggest practical advantage of an electromagnet over a permanent magnet?",
    "options": [
      "It is always cheaper",
      "It can be switched on and off, strengthened, and reversed using the current",
      "It never loses its magnetism",
      "It works without any electricity"
    ],
    "correctIndex": 1,
    "explanation": "An electromagnet's magnetism is created by the current, so you can control it completely — turn it on or off, vary its strength, and flip its poles. That command-on-demand is exactly what machines like cranes, relays, and motors need."
  },
  {
    "id": "physics/energy-transfer-and-efficiency",
    "contentSlug": "physics/energy-transfer-and-efficiency",
    "subject": "physics",
    "lessonTitle": "Energy Transfer & Efficiency",
    "prompt": "An electric motor takes in 100 J of electrical energy and delivers 85 J of mechanical work. The other 15 J became heat. What's its efficiency?",
    "options": [
      "15%",
      "85%",
      "100% — energy is always conserved",
      "It can't be calculated"
    ],
    "correctIndex": 1,
    "explanation": "Efficiency = useful out ÷ total in = 85 J ÷ 100 J = 0.85, or 85%. The 15 J of heat is energy that's conserved but no longer useful."
  },
  {
    "id": "physics/entropy-and-the-second-law",
    "contentSlug": "physics/entropy-and-the-second-law",
    "subject": "physics",
    "lessonTitle": "Entropy & the Second Law",
    "prompt": "Your freezer turns liquid water into highly-ordered ice crystals. Does this violate the Second Law?",
    "options": [
      "Yes — order increased, so entropy decreased",
      "No — the freezer pumps even more disorder (heat) into the room than the order it creates",
      "Yes, but only for water",
      "No, because ice has higher entropy than water"
    ],
    "correctIndex": 1,
    "explanation": "Local order is fine as long as total entropy rises. The freezer creates order inside but expels more than enough heat into the kitchen to increase the entropy of the whole system."
  },
  {
    "id": "physics/equivalence-principle",
    "contentSlug": "physics/equivalence-principle",
    "subject": "physics",
    "lessonTitle": "The Equivalence Principle",
    "prompt": "What does the equivalence principle state?",
    "options": [
      "Mass and energy are equivalent (E = mc²)",
      "Inside a sealed box, the effects of gravity and of steady acceleration are indistinguishable",
      "All observers measure the speed of light as equivalent",
      "Every action has an equal and opposite reaction"
    ],
    "correctIndex": 1,
    "explanation": "The equivalence principle says that locally, you cannot distinguish being at rest in a gravitational field from being uniformly accelerated. This led Einstein to predict that gravity bends light — confirmed in 1919 — and to reimagine gravity as curved spacetime rather than a force."
  },
  {
    "id": "physics/forces-pushes-and-pulls",
    "contentSlug": "physics/forces-pushes-and-pulls",
    "subject": "physics",
    "lessonTitle": "Forces — Pushes & Pulls",
    "prompt": "A crate is pushed with 10 N to the right and 4 N to the left. What is the net force?",
    "options": [
      "14 N right",
      "6 N right",
      "6 N left",
      "0 N"
    ],
    "correctIndex": 1,
    "explanation": "Along one line you add with direction: 10 N right − 4 N left = 6 N to the right."
  },
  {
    "id": "physics/frequency-and-period",
    "contentSlug": "physics/frequency-and-period",
    "subject": "physics",
    "lessonTitle": "Frequency & Period",
    "prompt": "A swing completes one full back-and-forth every 2 seconds. What is its frequency?",
    "options": [
      "2 Hz",
      "0.5 Hz",
      "1 Hz",
      "4 Hz"
    ],
    "correctIndex": 1,
    "explanation": "Frequency is the reciprocal of period: f = 1/T = 1/2 s = 0.5 Hz. It completes half a cycle each second."
  },
  {
    "id": "physics/friction",
    "contentSlug": "physics/friction",
    "subject": "physics",
    "lessonTitle": "Friction",
    "prompt": "A heavy box won't move until you push hard enough. The friction holding it still beforehand is:",
    "options": [
      "Kinetic friction",
      "Static friction",
      "Air resistance",
      "Gravity"
    ],
    "correctIndex": 1,
    "explanation": "Static friction grips a stationary object and matches your push up to a maximum. Once you exceed that, the box slides and kinetic friction takes over."
  },
  {
    "id": "physics/from-data-to-laws",
    "contentSlug": "physics/from-data-to-laws",
    "subject": "physics",
    "lessonTitle": "From Data to Laws",
    "prompt": "A new theory perfectly fits every measurement ever made, but forbids nothing and predicts no new result that could disprove it. From a scientific standpoint, what's its key weakness?",
    "options": [
      "It uses too much mathematics",
      "It isn't falsifiable, so it can't really be tested",
      "It agrees with the data too well",
      "It was proposed by only one person"
    ],
    "correctIndex": 1,
    "explanation": "A theory that can't be proven wrong by any conceivable experiment makes no risky predictions — and so tells us nothing we can check. Fitting old data is easy; the scientific value lies in bold, falsifiable predictions about results not yet seen."
  },
  {
    "id": "physics/galaxies-and-cosmic-scale",
    "contentSlug": "physics/galaxies-and-cosmic-scale",
    "subject": "physics",
    "lessonTitle": "Galaxies & the Cosmic Scale",
    "prompt": "What is the Milky Way?",
    "options": [
      "A nearby cloud of gas in the solar system",
      "Our galaxy — a disk of a few hundred billion stars, ~100,000 light-years across, that contains the Sun",
      "Another name for the Local Group of galaxies",
      "The band of planets along the ecliptic"
    ],
    "correctIndex": 1,
    "explanation": "The Milky Way is our home galaxy: a spiral disk of a few hundred billion stars about 100,000 light-years wide, with the Sun partway out along an arm. The faint band in the night sky is our view along the galaxy's disk from inside it."
  },
  {
    "id": "physics/gas-laws",
    "contentSlug": "physics/gas-laws",
    "subject": "physics",
    "lessonTitle": "The Gas Laws",
    "prompt": "A sealed syringe of gas is squeezed to half its volume at constant temperature. What happens to the pressure?",
    "options": [
      "It halves",
      "It stays the same",
      "It doubles",
      "It drops to zero"
    ],
    "correctIndex": 2,
    "explanation": "Boyle's Law: at constant temperature, P × V is constant. Halving the volume must double the pressure — the same particles hit the walls twice as often in the smaller space."
  },
  {
    "id": "physics/generators",
    "contentSlug": "physics/generators",
    "subject": "physics",
    "lessonTitle": "Generators",
    "prompt": "Why does a simple generator naturally produce alternating current (AC)?",
    "options": [
      "Because the magnets keep switching off",
      "Because as the coil rotates, the induced voltage rises, falls, and reverses each half-turn",
      "Because AC is stored in the coil",
      "Because the current runs out and comes back"
    ],
    "correctIndex": 1,
    "explanation": "As the coil spins, the flux through it changes direction every half rotation, so the induced voltage smoothly rises, drops to zero, and reverses — tracing out an alternating (sine) wave. One rotation gives one full AC cycle."
  },
  {
    "id": "physics/graphs-and-relationships",
    "contentSlug": "physics/graphs-and-relationships",
    "subject": "physics",
    "lessonTitle": "Graphs & Relationships",
    "prompt": "On a graph of distance (y) against time (x) for a car, the data form a straight line through the origin with a slope of 20. What does that tell you?",
    "options": [
      "The car is accelerating at 20 m/s²",
      "The car travels at a constant speed of 20 m/s",
      "The car covers 20 m in total",
      "Nothing — slope has no physical meaning"
    ],
    "correctIndex": 1,
    "explanation": "A straight line through the origin means distance is proportional to time. Its slope is Δdistance ÷ Δtime — a speed. A slope of 20 means a steady 20 m/s. (A curve would mean changing speed, i.e. acceleration.)"
  },
  {
    "id": "physics/gravity-and-free-fall",
    "contentSlug": "physics/gravity-and-free-fall",
    "subject": "physics",
    "lessonTitle": "Gravity & Free Fall",
    "prompt": "In a vacuum chamber, you release a hammer and a feather at the same instant. Which lands first?",
    "options": [
      "The hammer",
      "The feather",
      "They land at the same time",
      "The heavier one, always"
    ],
    "correctIndex": 2,
    "explanation": "With no air, both accelerate at the same g regardless of mass, so they land together. Air resistance is the only reason a feather normally lags."
  },
  {
    "id": "physics/heat-and-temperature",
    "contentSlug": "physics/heat-and-temperature",
    "subject": "physics",
    "lessonTitle": "Heat & Temperature",
    "prompt": "A lit match flame is much hotter than a swimming pool, yet the pool holds far more thermal energy. How is that possible?",
    "options": [
      "It's not — hotter always means more energy",
      "The pool has hugely more particles, so more total energy despite lower temperature",
      "Water can't store thermal energy",
      "The flame's energy doesn't count"
    ],
    "correctIndex": 1,
    "explanation": "Temperature is the average energy per particle; total thermal energy also depends on how many particles there are. The pool's enormous number of molecules outweighs the flame's higher per-particle energy."
  },
  {
    "id": "physics/heat-transfer",
    "contentSlug": "physics/heat-transfer",
    "subject": "physics",
    "lessonTitle": "Heat Transfer",
    "prompt": "The Sun's heat reaches Earth across the vacuum of space, where there are no particles. Which method of heat transfer must this be?",
    "options": [
      "Conduction — particle to particle",
      "Convection — carried by moving fluid",
      "Radiation — electromagnetic waves that need no medium",
      "None; heat can't cross a vacuum"
    ],
    "correctIndex": 2,
    "explanation": "Conduction and convection both need particles to carry the energy, so neither can cross empty space. Only radiation — energy travelling as electromagnetic (infrared and light) waves — can reach us through the vacuum."
  },
  {
    "id": "physics/how-circuits-work",
    "contentSlug": "physics/how-circuits-work",
    "subject": "physics",
    "lessonTitle": "How a Circuit Really Works",
    "prompt": "A light switch is metres from the bulb, yet the light comes on instantly even though electrons drift at under a millimetre per second. Why?",
    "options": [
      "The electrons actually travel at the speed of light",
      "The electric field propagates through the circuit at nearly light speed, nudging all electrons — including those in the bulb — into motion at once",
      "The bulb stores electrons in advance",
      "Light is produced by the switch itself"
    ],
    "correctIndex": 1,
    "explanation": "It's the electric field, not the electrons, that travels fast. Closing the switch sets up a field through the whole circuit almost instantly, so every electron — including those already in the filament — starts drifting at the same moment. The electrons themselves barely move."
  },
  {
    "id": "physics/inside-the-atom",
    "contentSlug": "physics/inside-the-atom",
    "subject": "physics",
    "lessonTitle": "Inside the Atom",
    "prompt": "What single property of an atom determines which element it is?",
    "options": [
      "The number of neutrons",
      "The number of electrons",
      "The number of protons",
      "The total mass of the atom"
    ],
    "correctIndex": 2,
    "explanation": "The proton count (the atomic number) defines the element. Change the neutrons and you get an isotope of the same element; change the electrons and you get an ion — but change the protons and it becomes a different element entirely."
  },
  {
    "id": "physics/inside-the-earth",
    "contentSlug": "physics/inside-the-earth",
    "subject": "physics",
    "lessonTitle": "Inside the Earth",
    "prompt": "Seismometers on the far side of the Earth from a quake detect P-waves but almost no S-waves. What does this reveal about the Earth's interior?",
    "options": [
      "The far side of the Earth is hollow",
      "There is a liquid layer (the outer core) that blocks the shear S-waves",
      "S-waves are simply weaker than P-waves",
      "The Earth's core is colder than its surface"
    ],
    "correctIndex": 1,
    "explanation": "S-waves can't propagate through liquid, so they're stopped by the molten outer core, leaving a shadow zone. P-waves pass through liquids and continue. The missing S-waves are the key evidence that the outer core is liquid."
  },
  {
    "id": "physics/interference-and-standing-waves",
    "contentSlug": "physics/interference-and-standing-waves",
    "subject": "physics",
    "lessonTitle": "Interference & Standing Waves",
    "prompt": "Two loudspeakers play the same steady tone. At certain spots in the room the sound is much louder; at others it nearly disappears. What's going on?",
    "options": [
      "The speakers are taking turns",
      "Interference — waves reinforce at some points and cancel at others",
      "The quiet spots have run out of energy",
      "Sound can't do that; it must be an echo"
    ],
    "correctIndex": 1,
    "explanation": "The two sound waves overlap and interfere. Where crests meet crests you get loud spots (constructive); where crests meet troughs the sound cancels (destructive). The total energy is just redistributed across the room."
  },
  {
    "id": "physics/isotopes",
    "contentSlug": "physics/isotopes",
    "subject": "physics",
    "lessonTitle": "Isotopes & Atomic Mass",
    "prompt": "Carbon-12 and carbon-14 are isotopes of the same element. How do they differ?",
    "options": [
      "Carbon-14 has more protons",
      "Carbon-14 has more neutrons, making it heavier",
      "Carbon-14 has more electrons and reacts differently",
      "They are completely different elements"
    ],
    "correctIndex": 1,
    "explanation": "Both have 6 protons (that's what makes them carbon), so they're chemically identical. Carbon-14 simply has two more neutrons than carbon-12, making it heavier — and, in this case, unstable."
  },
  {
    "id": "physics/kinetic-and-potential-energy",
    "contentSlug": "physics/kinetic-and-potential-energy",
    "subject": "physics",
    "lessonTitle": "Kinetic & Potential Energy",
    "prompt": "A swing rider reaches the highest point of their arc. At that exact instant…",
    "options": [
      "Kinetic energy is at its maximum",
      "Potential energy is at its maximum and kinetic is zero",
      "Both are at their maximum",
      "Both are zero"
    ],
    "correctIndex": 1,
    "explanation": "At the top of the arc the rider is momentarily still (no kinetic energy) but highest up (maximum potential). At the bottom it's the reverse."
  },
  {
    "id": "physics/kinetic-theory-of-gases",
    "contentSlug": "physics/kinetic-theory-of-gases",
    "subject": "physics",
    "lessonTitle": "The Kinetic Theory of Gases",
    "prompt": "In the kinetic theory, what does the pressure of a gas on its container actually consist of?",
    "options": [
      "A steady force the gas constantly exerts",
      "The combined effect of countless particle collisions with the walls every second",
      "The weight of the gas pressing down",
      "Attraction between the gas and the container"
    ],
    "correctIndex": 1,
    "explanation": "Pressure is the cumulative result of billions of particles striking the walls each second. More frequent or harder collisions (from less volume or higher temperature) mean higher pressure — which is exactly why the gas laws hold."
  },
  {
    "id": "physics/length-contraction",
    "contentSlug": "physics/length-contraction",
    "subject": "physics",
    "lessonTitle": "Length Contraction",
    "prompt": "A 100 m rocket flies past you at a speed where γ = 4. What length do you measure, and in which direction is it contracted?",
    "options": [
      "400 m, stretched along its motion",
      "25 m, contracted along its direction of motion (its height is unchanged)",
      "25 m, contracted in every direction equally",
      "100 m — length is the same for all observers"
    ],
    "correctIndex": 1,
    "explanation": "Length contracts by the factor γ: L = L₀/γ = 100/4 = 25 m. The contraction acts only along the direction of motion, so the rocket appears shortened front-to-back while its height and width stay the same."
  },
  {
    "id": "physics/lenses-and-images",
    "contentSlug": "physics/lenses-and-images",
    "subject": "physics",
    "lessonTitle": "Lenses & Images",
    "prompt": "You hold a magnifying glass (a convex lens) up to distant sunlight and it focuses to a tiny bright dot. What is that dot?",
    "options": [
      "The lens's centre of mass",
      "The focal point, where parallel rays converge",
      "A reflection of the Sun",
      "A shadow of the lens"
    ],
    "correctIndex": 1,
    "explanation": "A convex lens converges parallel rays (from the distant Sun) to its focal point. All that light concentrated on one spot is why it can start a fire."
  },
  {
    "id": "physics/life-of-a-star",
    "contentSlug": "physics/life-of-a-star",
    "subject": "physics",
    "lessonTitle": "The Life of a Star",
    "prompt": "What single property at a star's birth most determines how it will live and die?",
    "options": [
      "Its colour",
      "Its distance from other stars",
      "Its mass",
      "How fast it spins"
    ],
    "correctIndex": 2,
    "explanation": "A star's mass decides nearly everything: how hot and bright it burns, how long it lives, and its fate. Low-mass stars fade to white dwarfs; high-mass stars explode as supernovae and leave neutron stars or black holes."
  },
  {
    "id": "physics/magnets-and-fields",
    "contentSlug": "physics/magnets-and-fields",
    "subject": "physics",
    "lessonTitle": "Magnets & Magnetic Fields",
    "prompt": "You cut a bar magnet exactly in half through the middle. What do you get?",
    "options": [
      "A separate north pole and a separate south pole",
      "Two smaller magnets, each with its own north and south pole",
      "One magnet and one non-magnetic piece",
      "Two magnets with only north poles"
    ],
    "correctIndex": 1,
    "explanation": "Magnetic poles always come in pairs — you can't isolate one. Cutting a magnet just produces two complete, smaller magnets, each with a full north and south pole. Keep cutting and it keeps happening."
  },
  {
    "id": "physics/mass-energy",
    "contentSlug": "physics/mass-energy",
    "subject": "physics",
    "lessonTitle": "E = mc² and the Cosmic Speed Limit",
    "prompt": "Why can no spaceship ever reach the speed of light, no matter how powerful its engine?",
    "options": [
      "Its fuel would run out first",
      "Its mass would melt at high speed",
      "The energy needed grows toward infinity as v approaches c, so reaching c would take infinite energy",
      "Light would push back against it"
    ],
    "correctIndex": 2,
    "explanation": "An object's energy is E = γmc², and γ blows up toward infinity as v approaches c. Accelerating a massive object all the way to light speed would require infinite energy — impossible. Only massless things (like light) can travel at exactly c."
  },
  {
    "id": "physics/maxwell-and-em-waves",
    "contentSlug": "physics/maxwell-and-em-waves",
    "subject": "physics",
    "lessonTitle": "Maxwell's Unification & Electromagnetic Waves",
    "prompt": "What was the stunning conclusion when Maxwell calculated the speed of his predicted electromagnetic waves?",
    "options": [
      "They travelled instantly",
      "Their speed matched the measured speed of light — so light itself is an electromagnetic wave",
      "They moved slower than sound",
      "They could only travel through wires"
    ],
    "correctIndex": 1,
    "explanation": "Maxwell's wave speed, computed from the electric and magnetic constants, equalled the known speed of light. This revealed that light is an electromagnetic wave — unifying optics with electromagnetism, and predicting the entire spectrum from radio to gamma rays."
  },
  {
    "id": "physics/measuring-the-universe",
    "contentSlug": "physics/measuring-the-universe",
    "subject": "physics",
    "lessonTitle": "Measuring the Universe",
    "prompt": "Why is observing a very distant galaxy like looking back in time?",
    "options": [
      "Galaxies were created in the past and no longer exist",
      "Light travels at a finite speed, so we see the galaxy as it was when its light left, long ago",
      "Telescopes can rewind light",
      "Distant galaxies move backwards through time"
    ],
    "correctIndex": 1,
    "explanation": "Light travels fast but not instantly. A galaxy a billion light-years away is seen by light that left it a billion years ago — so we observe it as it was then, not now. The farther we look, the further back in time we see."
  },
  {
    "id": "physics/measuring-the-world",
    "contentSlug": "physics/measuring-the-world",
    "subject": "physics",
    "lessonTitle": "Measuring the World",
    "prompt": "Which of these is an SI base unit (not a derived one)?",
    "options": [
      "The newton (force)",
      "The metre per second (speed)",
      "The second (time)",
      "The square metre (area)"
    ],
    "correctIndex": 2,
    "explanation": "The second is one of the seven SI base units. The newton, m/s, and m² are all derived — built by combining base units (kg·m/s², m/s, and m×m respectively)."
  },
  {
    "id": "physics/momentum-and-collisions",
    "contentSlug": "physics/momentum-and-collisions",
    "subject": "physics",
    "lessonTitle": "Momentum & Collisions",
    "prompt": "Ball A moving right strikes an identical, stationary ball B head-on (elastic). What happens?",
    "options": [
      "A stops; B moves off at A's original speed",
      "They both move right at half speed",
      "A bounces straight back",
      "Both stop"
    ],
    "correctIndex": 0,
    "explanation": "For equal masses in an elastic head-on hit, the velocities swap: A stops and B leaves with A's original speed — total momentum is unchanged."
  },
  {
    "id": "physics/moon-and-eclipses",
    "contentSlug": "physics/moon-and-eclipses",
    "subject": "physics",
    "lessonTitle": "The Moon & Eclipses",
    "prompt": "Why don't we see a solar eclipse at every New Moon?",
    "options": [
      "The Moon is too far away to cast any shadow",
      "The Moon's orbit is tilted ~5°, so it usually passes above or below the Sun–Earth line and the shadow misses",
      "Solar eclipses only happen at Full Moon",
      "The Sun is only occasionally bright enough"
    ],
    "correctIndex": 1,
    "explanation": "A solar eclipse needs a New Moon AND a near-perfect alignment. Because the Moon's orbit is tilted about 5° relative to Earth's orbit, most New Moons the shadow passes just above or below Earth. Only when the three line up closely does an eclipse occur."
  },
  {
    "id": "physics/motion-graphs",
    "contentSlug": "physics/motion-graphs",
    "subject": "physics",
    "lessonTitle": "Reading Motion Graphs",
    "prompt": "On a position–time graph, what does a steeper (more vertical) line mean?",
    "options": [
      "The object is moving faster",
      "The object is moving slower",
      "The object is at rest",
      "The object is getting heavier"
    ],
    "correctIndex": 0,
    "explanation": "The slope of a position–time graph is the velocity, so a steeper line means more distance covered per second — i.e. moving faster."
  },
  {
    "id": "physics/motor-effect",
    "contentSlug": "physics/motor-effect",
    "subject": "physics",
    "lessonTitle": "The Motor Effect",
    "prompt": "A current-carrying wire sits between magnet poles and feels an upward force. You reverse BOTH the current and the field direction. What happens to the force?",
    "options": [
      "It now points downward",
      "It still points upward",
      "It disappears",
      "It points sideways"
    ],
    "correctIndex": 1,
    "explanation": "Reversing the current flips the force; reversing the field flips it again. Two flips cancel, so the force points the same way as before — still upward. (Reversing just one of them would flip it.)"
  },
  {
    "id": "physics/newtons-first-law",
    "contentSlug": "physics/newtons-first-law",
    "subject": "physics",
    "lessonTitle": "Newton's First Law (Inertia)",
    "prompt": "A puck slides across perfectly frictionless ice with no net force on it. What happens?",
    "options": [
      "It gradually slows down and stops",
      "It keeps moving in a straight line at constant speed",
      "It speeds up",
      "It immediately stops"
    ],
    "correctIndex": 1,
    "explanation": "With zero net force, inertia takes over: the puck keeps its velocity unchanged — straight line, constant speed, forever."
  },
  {
    "id": "physics/newtons-second-law",
    "contentSlug": "physics/newtons-second-law",
    "subject": "physics",
    "lessonTitle": "Newton's Second Law (F = ma)",
    "prompt": "A 2 kg cart feels a net force of 6 N. What is its acceleration?",
    "options": [
      "3 m/s²",
      "12 m/s²",
      "6 m/s²",
      "2 m/s²"
    ],
    "correctIndex": 0,
    "explanation": "Rearrange F = ma to a = F/m = 6 N ÷ 2 kg = 3 m/s²."
  },
  {
    "id": "physics/newtons-third-law",
    "contentSlug": "physics/newtons-third-law",
    "subject": "physics",
    "lessonTitle": "Newton's Third Law",
    "prompt": "You push on a wall with a force of 50 N. How hard does the wall push back on you?",
    "options": [
      "0 N — walls don't push",
      "50 N",
      "25 N",
      "100 N"
    ],
    "correctIndex": 1,
    "explanation": "By Newton's third law the wall pushes back with an equal and opposite force: exactly 50 N. (You don't move because other forces on you — like friction — are also in play.)"
  },
  {
    "id": "physics/nuclear-energy",
    "contentSlug": "physics/nuclear-energy",
    "subject": "physics",
    "lessonTitle": "Nuclear Energy: Fission & Fusion",
    "prompt": "Both fission and fusion release energy. What do they have in common?",
    "options": [
      "Both split heavy nuclei into lighter ones",
      "Both convert a small amount of mass into energy (E = mc²)",
      "Both join light nuclei into heavier ones",
      "Both require a chain reaction to release energy"
    ],
    "correctIndex": 1,
    "explanation": "Fission splits heavy nuclei and fusion joins light ones — opposite processes — but both move toward the tightly-bound 'iron valley' and release the lost mass as energy via E = mc². Only fission relies on a chain reaction."
  },
  {
    "id": "physics/ohms-law",
    "contentSlug": "physics/ohms-law",
    "subject": "physics",
    "lessonTitle": "Ohm's Law",
    "prompt": "A resistor has 6 V across it and 2 A flowing through it. What is its resistance?",
    "options": [
      "12 Ω",
      "3 Ω",
      "8 Ω",
      "0.33 Ω"
    ],
    "correctIndex": 1,
    "explanation": "Rearrange Ohm's law to R = V / I = 6 V ÷ 2 A = 3 Ω. The resistance is the ratio of the voltage across a component to the current through it."
  },
  {
    "id": "physics/orbits-and-gravitation",
    "contentSlug": "physics/orbits-and-gravitation",
    "subject": "physics",
    "lessonTitle": "Orbits & Universal Gravitation",
    "prompt": "What supplies the centripetal force that keeps a planet in its orbit?",
    "options": [
      "The planet's own spin",
      "Gravity from the star",
      "A push from the solar wind",
      "Nothing — it moves in a straight line"
    ],
    "correctIndex": 1,
    "explanation": "Gravity is the centripetal force. It continually bends the planet's straight-line motion into a closed orbit — an endless fall around the star."
  },
  {
    "id": "physics/power",
    "contentSlug": "physics/power",
    "subject": "physics",
    "lessonTitle": "Power",
    "prompt": "Elevator A and elevator B lift identical loads to the top floor. A takes 4 s, B takes 8 s. How do they compare?",
    "options": [
      "A does more work than B",
      "They do the same work, but A has twice the power",
      "B has more power because it runs longer",
      "They have the same power"
    ],
    "correctIndex": 1,
    "explanation": "Same load, same height → same work. A does it in half the time, so its power (work ÷ time) is twice as large."
  },
  {
    "id": "physics/powers-of-ten",
    "contentSlug": "physics/powers-of-ten",
    "subject": "physics",
    "lessonTitle": "Powers of Ten",
    "prompt": "A red blood cell is about 8 × 10⁻⁶ m wide. How is that written in full?",
    "options": [
      "8,000,000 m",
      "0.000008 m",
      "0.0000008 m",
      "8.0 m"
    ],
    "correctIndex": 1,
    "explanation": "A negative exponent means a small number: 10⁻⁶ shifts the decimal six places left, giving 0.000008 m — eight millionths of a metre. (That's why we usually just call it 8 micrometres.)"
  },
  {
    "id": "physics/precision-and-uncertainty",
    "contentSlug": "physics/precision-and-uncertainty",
    "subject": "physics",
    "lessonTitle": "Precision & Uncertainty",
    "prompt": "A kitchen scale always reads 50 g heavier than the true weight, but gives the same reading every time. How would you describe it?",
    "options": [
      "Accurate but not precise",
      "Precise but not accurate",
      "Both accurate and precise",
      "Neither accurate nor precise"
    ],
    "correctIndex": 1,
    "explanation": "Identical readings every time means high precision — but a fixed 50 g offset is a systematic error that makes every reading wrong, so it's not accurate. Averaging won't help; only re-zeroing the scale will."
  },
  {
    "id": "physics/pressure",
    "contentSlug": "physics/pressure",
    "subject": "physics",
    "lessonTitle": "Pressure",
    "prompt": "Why do snowshoes stop you from sinking into deep snow?",
    "options": [
      "They make you weigh less",
      "They spread your weight over a larger area, lowering the pressure on the snow",
      "They push the snow away with extra force",
      "They are filled with air"
    ],
    "correctIndex": 1,
    "explanation": "Your weight (the force) is unchanged, but snowshoes spread it over a much larger contact area. Since pressure = force ÷ area, the larger area means lower pressure — not enough to break through the snow."
  },
  {
    "id": "physics/pressure-in-fluids",
    "contentSlug": "physics/pressure-in-fluids",
    "subject": "physics",
    "lessonTitle": "Pressure in Fluids",
    "prompt": "Why is a dam built much thicker at its base than at its top?",
    "options": [
      "To look more impressive",
      "Water pressure increases with depth, so the base must withstand a much greater push",
      "The top would be too heavy otherwise",
      "Water is denser near the bottom"
    ],
    "correctIndex": 1,
    "explanation": "Fluid pressure grows with depth because of the weight of water above. The base of the dam holds back water under far higher pressure than the top, so it has to be stronger and thicker."
  },
  {
    "id": "physics/projectile-motion",
    "contentSlug": "physics/projectile-motion",
    "subject": "physics",
    "lessonTitle": "Projectile Motion",
    "prompt": "From the same height, you drop one ball and throw another horizontally at the very same instant. Which hits the ground first?",
    "options": [
      "The dropped ball",
      "The thrown ball",
      "They land at the same time",
      "It depends how hard you throw"
    ],
    "correctIndex": 2,
    "explanation": "Vertical and horizontal motion are independent. Both balls start with zero vertical velocity and fall under the same gravity, so they hit the ground together — the throw only changes where, not when."
  },
  {
    "id": "physics/quantum-leap",
    "contentSlug": "physics/quantum-leap",
    "subject": "physics",
    "lessonTitle": "The Quantum Leap: Light as Particles",
    "prompt": "A dim violet light ejects electrons from a metal, but an intensely bright red light ejects none. Why?",
    "options": [
      "Red light moves too slowly to reach the metal",
      "Each red photon has too little energy (low frequency); brightness only adds more of these too-weak photons",
      "Bright light reflects off the metal instead of being absorbed",
      "Violet light is a wave but red light is not"
    ],
    "correctIndex": 1,
    "explanation": "One electron is freed by one photon. A red photon's energy (E = hf) is below the metal's threshold, so it can't eject an electron — and piling on more red photons by brightening the light never helps. A violet photon has a higher frequency, hence enough energy, even when the light is dim."
  },
  {
    "id": "physics/quantum-world",
    "contentSlug": "physics/quantum-world",
    "subject": "physics",
    "lessonTitle": "Into the Quantum World",
    "prompt": "In the single-particle double-slit experiment, why do the interference bands disappear when you add a detector that records which slit each particle goes through?",
    "options": [
      "The detector physically blocks one of the slits",
      "Measuring the path collapses the superposition, so the particle no longer goes through both slits at once",
      "The detector slows the particles down too much",
      "Interference only works for large numbers of particles at once"
    ],
    "correctIndex": 1,
    "explanation": "The interference relies on each particle being in a superposition of both paths. Measuring which slit it took collapses that superposition to a single definite path, so there's nothing left to interfere — and the wave pattern vanishes. Observation itself changes the outcome."
  },
  {
    "id": "physics/radioactive-decay",
    "contentSlug": "physics/radioactive-decay",
    "subject": "physics",
    "lessonTitle": "Radioactive Decay & Half-Life",
    "prompt": "An isotope has a half-life of 8 days. You start with 80 mg. How much remains after 24 days?",
    "options": [
      "40 mg",
      "20 mg",
      "10 mg",
      "0 mg — it's all gone"
    ],
    "correctIndex": 2,
    "explanation": "24 days is three half-lives (24 ÷ 8 = 3). Halve three times: 80 → 40 → 20 → 10 mg. Each half-life removes half of whatever is left, so the sample shrinks but never quite hits zero."
  },
  {
    "id": "physics/radioactivity",
    "contentSlug": "physics/radioactivity",
    "subject": "physics",
    "lessonTitle": "What Is Radioactivity?",
    "prompt": "You need shielding that stops alpha and beta radiation but you're not worried about gamma. Roughly what's the least you need?",
    "options": [
      "A sheet of paper is enough for both",
      "A few millimetres of aluminium",
      "Several centimetres of lead",
      "Nothing can stop beta radiation"
    ],
    "correctIndex": 1,
    "explanation": "Paper stops alpha but lets beta through. A few millimetres of aluminium stops both alpha and beta. Gamma is the penetrating one — it takes dense lead (and even then is only weakened, not fully blocked)."
  },
  {
    "id": "physics/reflection-and-mirrors",
    "contentSlug": "physics/reflection-and-mirrors",
    "subject": "physics",
    "lessonTitle": "Reflection & Mirrors",
    "prompt": "A ray of light strikes a mirror at 30° to the normal. At what angle to the normal does it reflect?",
    "options": [
      "60°",
      "30°",
      "0°",
      "90°"
    ],
    "correctIndex": 1,
    "explanation": "The law of reflection says the angle of reflection equals the angle of incidence — both measured from the normal. 30° in, 30° out."
  },
  {
    "id": "physics/reflection-and-refraction",
    "contentSlug": "physics/reflection-and-refraction",
    "subject": "physics",
    "lessonTitle": "Reflection & Refraction",
    "prompt": "A light wave passes from air into glass, where it travels more slowly. Its frequency stays the same. What happens to its wavelength?",
    "options": [
      "It gets longer",
      "It gets shorter",
      "It stays exactly the same",
      "It drops to zero"
    ],
    "correctIndex": 1,
    "explanation": "With frequency fixed and v = fλ, a lower speed means a shorter wavelength. The wavefronts bunch closer together, which is what bends the wave toward the normal."
  },
  {
    "id": "physics/refraction-bending-light",
    "contentSlug": "physics/refraction-bending-light",
    "subject": "physics",
    "lessonTitle": "Refraction — Bending Light",
    "prompt": "A light ray passes from air into a glass block (where it travels more slowly), striking the surface at an angle. How does it bend?",
    "options": [
      "Toward the normal",
      "Away from the normal",
      "It doesn't bend at all",
      "It bounces straight back"
    ],
    "correctIndex": 0,
    "explanation": "Entering a slower medium (higher refractive index), light bends toward the normal. Leaving into a faster medium, it would bend away."
  },
  {
    "id": "physics/relativity-of-simultaneity",
    "contentSlug": "physics/relativity-of-simultaneity",
    "subject": "physics",
    "lessonTitle": "The Relativity of Simultaneity",
    "prompt": "Two events are simultaneous for an observer standing still. For an observer moving past at high speed, the events are...",
    "options": [
      "Always still simultaneous — simultaneity is absolute",
      "Generally NOT simultaneous; their timing and even order can differ",
      "Simultaneous only if they happen in the same place",
      "Impossible to observe at all"
    ],
    "correctIndex": 1,
    "explanation": "Simultaneity is relative. Events that are simultaneous in one frame are generally not simultaneous in another moving relative to it — and for widely separated events the order can even reverse. (Causally connected events, which light can bridge, always keep their order.)"
  },
  {
    "id": "physics/relativity-postulates",
    "contentSlug": "physics/relativity-postulates",
    "subject": "physics",
    "lessonTitle": "The Speed of Light Is Absolute",
    "prompt": "A spaceship moving at half the speed of light fires a laser straight ahead. How fast does the laser's light travel as measured by a stationary observer it passes?",
    "options": [
      "1.5 × c — the ship's speed adds to the light",
      "Exactly c — the same as if the ship were at rest",
      "0.5 × c — slower, because of the ship's motion",
      "It depends on the colour of the laser"
    ],
    "correctIndex": 1,
    "explanation": "By Einstein's second postulate, every observer measures light in a vacuum at exactly c, regardless of the source's motion. Unlike a thrown ball, the ship's speed does NOT add to the light. Keeping c constant for everyone is what forces space and time to be relative."
  },
  {
    "id": "physics/resistance",
    "contentSlug": "physics/resistance",
    "subject": "physics",
    "lessonTitle": "Resistance",
    "prompt": "You replace a short, thick copper wire with a long, thin one of the same metal. What happens to its resistance?",
    "options": [
      "It decreases",
      "It increases",
      "It stays the same",
      "It depends on the voltage"
    ],
    "correctIndex": 1,
    "explanation": "Longer wires and thinner wires both increase resistance — more length means more collisions, and less cross-section gives electrons less room. Making the wire both longer and thinner raises its resistance substantially."
  },
  {
    "id": "physics/semiconductors",
    "contentSlug": "physics/semiconductors",
    "subject": "physics",
    "lessonTitle": "Semiconductors: The Physics of the Chip",
    "prompt": "Why can a semiconductor be switched between conducting and non-conducting, while a metal is always a conductor?",
    "options": [
      "A semiconductor has no electrons at all until you switch it on",
      "A metal's bands overlap, but a semiconductor has a small gap electrons can be made to cross — or not",
      "Semiconductors are liquids and metals are solids",
      "Metals are doped and semiconductors are pure"
    ],
    "correctIndex": 1,
    "explanation": "In a metal the conduction band is already accessible, so it always conducts. A semiconductor has a small band gap: with no extra energy its electrons stay put (insulator-like), but heat, light, doping, or an applied voltage can push them across — letting us switch conduction on and off."
  },
  {
    "id": "physics/series-and-parallel-circuits",
    "contentSlug": "physics/series-and-parallel-circuits",
    "subject": "physics",
    "lessonTitle": "Series & Parallel Circuits",
    "prompt": "Two identical bulbs are wired in parallel across a battery. You unscrew one. What happens to the other?",
    "options": [
      "It goes out too",
      "It keeps glowing at the same brightness",
      "It gets dimmer",
      "It gets brighter"
    ],
    "correctIndex": 1,
    "explanation": "In parallel, each bulb has its own independent loop to the battery and gets the full voltage. Removing one bulb only breaks its own branch — the other bulb's circuit is untouched, so it stays just as bright."
  },
  {
    "id": "physics/simple-harmonic-motion",
    "contentSlug": "physics/simple-harmonic-motion",
    "subject": "physics",
    "lessonTitle": "Why a Pendulum Swings",
    "prompt": "You double the length L of the pendulum. What happens to the period T?",
    "options": [
      "It doubles",
      "It increases by about 1.4×",
      "It halves",
      "It stays exactly the same"
    ],
    "correctIndex": 1,
    "explanation": "Since T is proportional to √L, doubling L multiplies the period by √2 ≈ 1.41 — not by 2."
  },
  {
    "id": "physics/sound",
    "contentSlug": "physics/sound",
    "subject": "physics",
    "lessonTitle": "Sound",
    "prompt": "An astronaut outside the ISS bangs two metal plates together. A nearby astronaut in the vacuum…",
    "options": [
      "Hears a loud clang",
      "Hears nothing — there's no air to carry the sound",
      "Hears it faintly, delayed",
      "Hears it only through their helmet radio"
    ],
    "correctIndex": 1,
    "explanation": "Sound is a pressure wave that needs a medium. In the vacuum of space there are no particles to compress, so the clang makes no sound at all (a radio link is the only way to hear it)."
  },
  {
    "id": "physics/speed-and-velocity",
    "contentSlug": "physics/speed-and-velocity",
    "subject": "physics",
    "lessonTitle": "Speed & Velocity",
    "prompt": "Which of these describes a velocity, not just a speed?",
    "options": [
      "50 km/h",
      "50 km/h heading north",
      "Really fast",
      "100 metres"
    ],
    "correctIndex": 1,
    "explanation": "Velocity needs a direction. '50 km/h heading north' has both a size and a direction; '50 km/h' alone is just speed."
  },
  {
    "id": "physics/standard-model",
    "contentSlug": "physics/standard-model",
    "subject": "physics",
    "lessonTitle": "The Particle Zoo & the Standard Model",
    "prompt": "In the Standard Model, what is a proton actually made of?",
    "options": [
      "A single fundamental, indivisible particle",
      "Three quarks (two up and one down) bound by gluons",
      "Two electrons and a neutrino",
      "A Higgs boson and a photon"
    ],
    "correctIndex": 1,
    "explanation": "A proton is not fundamental — it's a bound trio of quarks (up, up, down) held together by the strong force, carried by gluons. The electron, by contrast, is fundamental as far as we know."
  },
  {
    "id": "physics/states-of-matter",
    "contentSlug": "physics/states-of-matter",
    "subject": "physics",
    "lessonTitle": "States of Matter",
    "prompt": "A gas takes the shape AND the volume of any container it's in, while a liquid only takes the shape. What explains the difference?",
    "options": [
      "Gas particles are heavier than liquid particles",
      "Gas particles have broken free and fly apart to fill all available space; liquid particles still touch",
      "Liquids have no particles",
      "Gas particles are stuck in a fixed pattern"
    ],
    "correctIndex": 1,
    "explanation": "In a liquid the particles still touch and hold a fixed volume, just sliding around to fit the shape. In a gas they've separated entirely and spread out to fill whatever space they can reach."
  },
  {
    "id": "physics/static-electricity",
    "contentSlug": "physics/static-electricity",
    "subject": "physics",
    "lessonTitle": "Static Electricity",
    "prompt": "You rub a plastic rod with a cloth and the rod becomes negatively charged. What happened?",
    "options": [
      "Protons moved from the cloth onto the rod",
      "Electrons were transferred from the cloth onto the rod",
      "The rod created new charge",
      "The rod lost electrons to the cloth"
    ],
    "correctIndex": 1,
    "explanation": "Charging by friction transfers electrons, not protons. A negatively charged rod has gained extra electrons from the cloth, which is left positively charged. Charge isn't created — just moved."
  },
  {
    "id": "physics/superconductivity",
    "contentSlug": "physics/superconductivity",
    "subject": "physics",
    "lessonTitle": "Superconductivity",
    "prompt": "A magnet floats motionless above a chilled superconductor. Which property is responsible — beyond simply having low resistance?",
    "options": [
      "The superconductor is also a strong permanent magnet",
      "The Meissner effect — the superconductor expels magnetic field from its interior",
      "Cold air under the magnet holds it up",
      "Gravity is weaker at low temperatures"
    ],
    "correctIndex": 1,
    "explanation": "A superconductor actively expels magnetic fields (the Meissner effect), not just conducts well. The excluded field pushes back on the magnet, suspending it on a stable, frictionless cushion — a distinct quantum behaviour, not mere zero resistance."
  },
  {
    "id": "physics/the-electromagnetic-spectrum",
    "contentSlug": "physics/the-electromagnetic-spectrum",
    "subject": "physics",
    "lessonTitle": "The Electromagnetic Spectrum",
    "prompt": "Gamma rays have a much shorter wavelength than radio waves. How do their speed and energy compare (in a vacuum)?",
    "options": [
      "Gamma rays travel faster and carry more energy",
      "Same speed (c), but gamma rays carry more energy",
      "Gamma rays travel slower but carry more energy",
      "They're identical in every way"
    ],
    "correctIndex": 1,
    "explanation": "All electromagnetic waves travel at c in a vacuum. Shorter wavelength means higher frequency and therefore more energy — so gamma rays are far more energetic than radio waves, but no faster."
  },
  {
    "id": "physics/the-expanding-universe",
    "contentSlug": "physics/the-expanding-universe",
    "subject": "physics",
    "lessonTitle": "The Expanding Universe",
    "prompt": "Distant galaxies are redshifted, and farther ones more so. What's the best explanation?",
    "options": [
      "We are at the exact center of the universe and everything flies away from us",
      "Space itself is expanding, stretching light and carrying galaxies apart — so every observer sees the same thing",
      "All galaxies are heating up and turning red",
      "The galaxies are falling toward a giant mass behind us"
    ],
    "correctIndex": 1,
    "explanation": "The expansion of space stretches the light travelling through it (redshift) and carries galaxies apart, with speed proportional to distance (Hubble's law, v = H₀d). Because there's no center, every observer — anywhere — sees all other galaxies receding, faster with distance."
  },
  {
    "id": "physics/the-moving-sky",
    "contentSlug": "physics/the-moving-sky",
    "subject": "physics",
    "lessonTitle": "The Moving Sky",
    "prompt": "What causes the seasons on Earth?",
    "options": [
      "The Earth being closer to the Sun in summer and farther in winter",
      "The Earth's 23.5° axial tilt, which makes a hemisphere lean toward or away from the Sun",
      "The Sun getting hotter and cooler over the year",
      "The Earth speeding up and slowing down in its orbit"
    ],
    "correctIndex": 1,
    "explanation": "Seasons come from the axial tilt, not distance. The axis points the same way all year, so each hemisphere alternately leans toward the Sun (direct light, long days, summer) and away from it (winter) — which is also why the two hemispheres have opposite seasons."
  },
  {
    "id": "physics/the-solar-system",
    "contentSlug": "physics/the-solar-system",
    "subject": "physics",
    "lessonTitle": "The Solar System",
    "prompt": "Which planet orbits the Sun fastest, and why?",
    "options": [
      "Neptune, because it is the largest and has the most momentum",
      "Mercury, because it is closest to the Sun (Kepler's third law: nearer planets orbit faster)",
      "Jupiter, because its strong gravity pulls it along",
      "They all orbit at the same speed"
    ],
    "correctIndex": 1,
    "explanation": "By Kepler's third law, the closer a planet is to the Sun, the faster it orbits. Mercury, the innermost planet, races around in just 88 days, while distant Neptune takes 165 years — a direct consequence of gravity weakening with distance."
  },
  {
    "id": "physics/time-dilation",
    "contentSlug": "physics/time-dilation",
    "subject": "physics",
    "lessonTitle": "Time Dilation",
    "prompt": "Why does a moving light clock tick more slowly than an identical one at rest?",
    "options": [
      "The mirrors get heavier and respond more sluggishly when moving",
      "The photon travels a longer diagonal path but can't exceed c, so each tick takes longer",
      "Moving light actually slows down below c",
      "The photon loses energy each time it bounces"
    ],
    "correctIndex": 1,
    "explanation": "To an outside observer the moving clock's photon must travel a longer, diagonal path. Since its speed is fixed at c and can't increase, covering the extra distance takes more time — so each tick lengthens. Time itself runs slow for the moving clock."
  },
  {
    "id": "physics/transformers",
    "contentSlug": "physics/transformers",
    "subject": "physics",
    "lessonTitle": "Transformers & the Grid",
    "prompt": "Why does the power grid step voltage UP to very high values for long-distance transmission?",
    "options": [
      "High voltage travels faster",
      "Higher voltage means lower current, and energy lost in the cables (I²R) falls sharply with less current",
      "It makes the electricity stronger",
      "Transformers only work at high voltage"
    ],
    "correctIndex": 1,
    "explanation": "For a given power, raising the voltage lowers the current. Since cable losses go as I²R, reducing the current sharply reduces wasted energy. The grid transmits at very high voltage, then steps it down near homes for safety."
  },
  {
    "id": "physics/units-and-conversion",
    "contentSlug": "physics/units-and-conversion",
    "subject": "physics",
    "lessonTitle": "Units, Prefixes & Conversion",
    "prompt": "A film of dust is 0.5 mm thick. How many micrometres (µm) is that?",
    "options": [
      "0.0005 µm",
      "5 µm",
      "500 µm",
      "5000 µm"
    ],
    "correctIndex": 2,
    "explanation": "1 mm = 1000 µm (milli is 10⁻³, micro is 10⁻⁶, so they differ by a factor of 1000). Thus 0.5 mm × 1000 = 500 µm."
  },
  {
    "id": "physics/voltage",
    "contentSlug": "physics/voltage",
    "subject": "physics",
    "lessonTitle": "Voltage",
    "prompt": "In the water-circuit analogy, voltage is most like which quantity?",
    "options": [
      "The amount of water in the pipes",
      "The pressure from the pump that drives the water around",
      "The width of the pipe",
      "The temperature of the water"
    ],
    "correctIndex": 1,
    "explanation": "Voltage is the 'push' that drives charge around a circuit, just as pump pressure drives water through pipes. Current corresponds to the flow rate, and resistance to how narrow the pipe is."
  },
  {
    "id": "physics/wave-optics",
    "contentSlug": "physics/wave-optics",
    "subject": "physics",
    "lessonTitle": "Wave Optics: Diffraction & Interference",
    "prompt": "In a double-slit experiment, you see bright and dark bands on the screen. What does a DARK band tell you about the light arriving there from the two slits?",
    "options": [
      "No light left the slits in that direction",
      "The two waves arrived out of step and cancelled (destructive interference)",
      "The screen absorbed the light there",
      "One slit was blocked"
    ],
    "correctIndex": 1,
    "explanation": "A dark band is destructive interference: light reaches it from both slits, but with a path difference of half a wavelength, so crest meets trough and the waves cancel. The energy is redistributed into the bright bands."
  },
  {
    "id": "physics/wave-particle-duality",
    "contentSlug": "physics/wave-particle-duality",
    "subject": "physics",
    "lessonTitle": "Wave–Particle Duality & the Atom",
    "prompt": "Why can an atom's electron only have certain specific energies?",
    "options": [
      "Because the nucleus physically blocks other energies",
      "Because only a whole number of electron-wavelengths can fit into a stable standing wave, like harmonics on a string",
      "Because electrons are too small to measure precisely",
      "Because energy is always a whole number of joules"
    ],
    "correctIndex": 1,
    "explanation": "Treating the electron as a wave, only states where a whole number of wavelengths fits form a stable standing wave — exactly like the harmonics of a guitar string. The in-between energies don't form a stable wave, so they're forbidden, giving the atom its discrete energy levels."
  },
  {
    "id": "physics/wave-speed",
    "contentSlug": "physics/wave-speed",
    "subject": "physics",
    "lessonTitle": "Wave Speed (v = fλ)",
    "prompt": "A sound wave has frequency 170 Hz and travels at 343 m/s in air. Roughly what is its wavelength?",
    "options": [
      "About 2 m",
      "About 0.5 m",
      "About 58,000 m",
      "About 170 m"
    ],
    "correctIndex": 0,
    "explanation": "λ = v / f = 343 / 170 ≈ 2 m. Rearranging v = fλ lets you find any one quantity from the other two."
  },
  {
    "id": "physics/waves-and-wavelength",
    "contentSlug": "physics/waves-and-wavelength",
    "subject": "physics",
    "lessonTitle": "Waves & Wavelength",
    "prompt": "A cork floats on rippling water. As the waves pass beneath it, the cork mostly…",
    "options": [
      "Travels along with the waves to the far side",
      "Bobs up and down roughly in place",
      "Sinks under each crest",
      "Speeds up over time"
    ],
    "correctIndex": 1,
    "explanation": "Waves carry energy, not matter. The water — and the cork on it — just oscillates in place while the disturbance moves through."
  },
  {
    "id": "physics/what-is-energy",
    "contentSlug": "physics/what-is-energy",
    "subject": "physics",
    "lessonTitle": "What Is Energy?",
    "prompt": "A skateboarder coasts down a ramp, speeding up as they drop. What's happening to their energy?",
    "options": [
      "Energy is being created out of nothing",
      "Stored height energy is turning into energy of motion",
      "Energy is being destroyed as they speed up",
      "Nothing — energy isn't involved in motion"
    ],
    "correctIndex": 1,
    "explanation": "As the skater drops, stored (potential) energy converts into kinetic energy. The total doesn't change — it just switches form."
  },
  {
    "id": "physics/what-is-light",
    "contentSlug": "physics/what-is-light",
    "subject": "physics",
    "lessonTitle": "What Is Light?",
    "prompt": "Why does a tree cast a sharp-edged shadow on a sunny day?",
    "options": [
      "Light bends around the tree",
      "Light travels in straight lines, so the tree blocks the rays directly behind it",
      "The ground absorbs the light",
      "Shadows are made of darkness flowing out of the tree"
    ],
    "correctIndex": 1,
    "explanation": "Light travels in straight rays. The tree blocks the rays heading straight past it, leaving an unlit region — the shadow — with a crisp edge."
  },
  {
    "id": "physics/what-is-motion",
    "contentSlug": "physics/what-is-motion",
    "subject": "physics",
    "lessonTitle": "What Is Motion?",
    "prompt": "You walk 8 m east, then 3 m west. What is your displacement?",
    "options": [
      "11 m",
      "5 m east",
      "5 m west",
      "0 m"
    ],
    "correctIndex": 1,
    "explanation": "Distance is 8 + 3 = 11 m, but displacement is the net change: 8 east − 3 west = 5 m east. Displacement always keeps the direction."
  },
  {
    "id": "physics/what-is-physics",
    "contentSlug": "physics/what-is-physics",
    "subject": "physics",
    "lessonTitle": "What Is Physics?",
    "prompt": "Which of these is a properly scientific hypothesis?",
    "options": [
      "Everything happens for a reason we can never know",
      "A dropped ball and a dropped feather fall at the same rate in a vacuum",
      "The universe is fundamentally beautiful",
      "There is an undetectable force that explains anything you observe"
    ],
    "correctIndex": 1,
    "explanation": "It's testable and falsifiable — you could put a ball and feather in a vacuum chamber and see. (They do fall together, as the famous Apollo 15 Moon demo showed.) The others can't be proved wrong by any experiment, so science can't weigh in."
  },
  {
    "id": "physics/work-force-and-distance",
    "contentSlug": "physics/work-force-and-distance",
    "subject": "physics",
    "lessonTitle": "Work = Force × Distance",
    "prompt": "You push against a parked car with all your strength for a minute, but it doesn't budge. How much work did you do on the car?",
    "options": [
      "A lot — you pushed very hard",
      "Zero — it didn't move",
      "It depends on how tired you are",
      "Half, because you tried"
    ],
    "correctIndex": 1,
    "explanation": "Work = force × distance. With zero distance moved, the work done on the car is zero — no matter how hard you pushed."
  }
]
