/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSubjectSlugRouteImport } from './routes/subjects.$subjectSlug'
import { Route as LearnSplatRouteImport } from './routes/learn.$'
import { Route as SubjectsSubjectSlugIndexRouteImport } from './routes/subjects.$subjectSlug.index'
import { Route as SubjectsSubjectSlugUnitSlugRouteImport } from './routes/subjects.$subjectSlug.$unitSlug'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectSlugRoute = SubjectsSubjectSlugRouteImport.update({
  id: '/subjects/$subjectSlug',
  path: '/subjects/$subjectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSplatRoute = LearnSplatRouteImport.update({
  id: '/learn/$',
  path: '/learn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectSlugIndexRoute =
  SubjectsSubjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SubjectsSubjectSlugRoute,
  } as any)
const SubjectsSubjectSlugUnitSlugRoute =
  SubjectsSubjectSlugUnitSlugRouteImport.update({
    id: '/$unitSlug',
    path: '/$unitSlug',
    getParentRoute: () => SubjectsSubjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/learn/$': typeof LearnSplatRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRouteWithChildren
  '/subjects/$subjectSlug/$unitSlug': typeof SubjectsSubjectSlugUnitSlugRoute
  '/subjects/$subjectSlug/': typeof SubjectsSubjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/learn/$': typeof LearnSplatRoute
  '/subjects/$subjectSlug/$unitSlug': typeof SubjectsSubjectSlugUnitSlugRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/learn/$': typeof LearnSplatRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRouteWithChildren
  '/subjects/$subjectSlug/$unitSlug': typeof SubjectsSubjectSlugUnitSlugRoute
  '/subjects/$subjectSlug/': typeof SubjectsSubjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/dashboard'
    | '/discover'
    | '/leaderboard'
    | '/login'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/upgrade'
    | '/learn/$'
    | '/subjects/$subjectSlug'
    | '/subjects/$subjectSlug/$unitSlug'
    | '/subjects/$subjectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/dashboard'
    | '/discover'
    | '/leaderboard'
    | '/login'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/upgrade'
    | '/learn/$'
    | '/subjects/$subjectSlug/$unitSlug'
    | '/subjects/$subjectSlug'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/dashboard'
    | '/discover'
    | '/leaderboard'
    | '/login'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/upgrade'
    | '/learn/$'
    | '/subjects/$subjectSlug'
    | '/subjects/$subjectSlug/$unitSlug'
    | '/subjects/$subjectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  UpgradeRoute: typeof UpgradeRoute
  LearnSplatRoute: typeof LearnSplatRoute
  SubjectsSubjectSlugRoute: typeof SubjectsSubjectSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectSlug': {
      id: '/subjects/$subjectSlug'
      path: '/subjects/$subjectSlug'
      fullPath: '/subjects/$subjectSlug'
      preLoaderRoute: typeof SubjectsSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$': {
      id: '/learn/$'
      path: '/learn/$'
      fullPath: '/learn/$'
      preLoaderRoute: typeof LearnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectSlug/': {
      id: '/subjects/$subjectSlug/'
      path: '/'
      fullPath: '/subjects/$subjectSlug/'
      preLoaderRoute: typeof SubjectsSubjectSlugIndexRouteImport
      parentRoute: typeof SubjectsSubjectSlugRoute
    }
    '/subjects/$subjectSlug/$unitSlug': {
      id: '/subjects/$subjectSlug/$unitSlug'
      path: '/$unitSlug'
      fullPath: '/subjects/$subjectSlug/$unitSlug'
      preLoaderRoute: typeof SubjectsSubjectSlugUnitSlugRouteImport
      parentRoute: typeof SubjectsSubjectSlugRoute
    }
  }
}

interface SubjectsSubjectSlugRouteChildren {
  SubjectsSubjectSlugUnitSlugRoute: typeof SubjectsSubjectSlugUnitSlugRoute
  SubjectsSubjectSlugIndexRoute: typeof SubjectsSubjectSlugIndexRoute
}

const SubjectsSubjectSlugRouteChildren: SubjectsSubjectSlugRouteChildren = {
  SubjectsSubjectSlugUnitSlugRoute: SubjectsSubjectSlugUnitSlugRoute,
  SubjectsSubjectSlugIndexRoute: SubjectsSubjectSlugIndexRoute,
}

const SubjectsSubjectSlugRouteWithChildren =
  SubjectsSubjectSlugRoute._addFileChildren(SubjectsSubjectSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  UpgradeRoute: UpgradeRoute,
  LearnSplatRoute: LearnSplatRoute,
  SubjectsSubjectSlugRoute: SubjectsSubjectSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
