/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSubjectSlugRouteImport } from './routes/subjects.$subjectSlug'
import { Route as LearnSplatRouteImport } from './routes/learn.$'
import { Route as SubjectsSubjectSlugIndexRouteImport } from './routes/subjects.$subjectSlug.index'
import { Route as SubjectsSubjectSlugUnitSlugRouteImport } from './routes/subjects.$subjectSlug.$unitSlug'

const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectSlugRoute = SubjectsSubjectSlugRouteImport.update({
  id: '/subjects/$subjectSlug',
  path: '/subjects/$subjectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSplatRoute = LearnSplatRouteImport.update({
  id: '/learn/$',
  path: '/learn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectSlugIndexRoute =
  SubjectsSubjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SubjectsSubjectSlugRoute,
  } as any)
const SubjectsSubjectSlugUnitSlugRoute =
  SubjectsSubjectSlugUnitSlugRouteImport.update({
    id: '/$unitSlug',
    path: '/$unitSlug',
    getParentRoute: () => SubjectsSubjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/learn/$': typeof LearnSplatRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRouteWithChildren
  '/subjects/$subjectSlug/$unitSlug': typeof SubjectsSubjectSlugUnitSlugRoute
  '/subjects/$subjectSlug/': typeof SubjectsSubjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/learn/$': typeof LearnSplatRoute
  '/subjects/$subjectSlug/$unitSlug': typeof SubjectsSubjectSlugUnitSlugRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/learn/$': typeof LearnSplatRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRouteWithChildren
  '/subjects/$subjectSlug/$unitSlug': typeof SubjectsSubjectSlugUnitSlugRoute
  '/subjects/$subjectSlug/': typeof SubjectsSubjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/learn/$'
    | '/subjects/$subjectSlug'
    | '/subjects/$subjectSlug/$unitSlug'
    | '/subjects/$subjectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/learn/$'
    | '/subjects/$subjectSlug/$unitSlug'
    | '/subjects/$subjectSlug'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/learn/$'
    | '/subjects/$subjectSlug'
    | '/subjects/$subjectSlug/$unitSlug'
    | '/subjects/$subjectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  LearnSplatRoute: typeof LearnSplatRoute
  SubjectsSubjectSlugRoute: typeof SubjectsSubjectSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectSlug': {
      id: '/subjects/$subjectSlug'
      path: '/subjects/$subjectSlug'
      fullPath: '/subjects/$subjectSlug'
      preLoaderRoute: typeof SubjectsSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$': {
      id: '/learn/$'
      path: '/learn/$'
      fullPath: '/learn/$'
      preLoaderRoute: typeof LearnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectSlug/': {
      id: '/subjects/$subjectSlug/'
      path: '/'
      fullPath: '/subjects/$subjectSlug/'
      preLoaderRoute: typeof SubjectsSubjectSlugIndexRouteImport
      parentRoute: typeof SubjectsSubjectSlugRoute
    }
    '/subjects/$subjectSlug/$unitSlug': {
      id: '/subjects/$subjectSlug/$unitSlug'
      path: '/$unitSlug'
      fullPath: '/subjects/$subjectSlug/$unitSlug'
      preLoaderRoute: typeof SubjectsSubjectSlugUnitSlugRouteImport
      parentRoute: typeof SubjectsSubjectSlugRoute
    }
  }
}

interface SubjectsSubjectSlugRouteChildren {
  SubjectsSubjectSlugUnitSlugRoute: typeof SubjectsSubjectSlugUnitSlugRoute
  SubjectsSubjectSlugIndexRoute: typeof SubjectsSubjectSlugIndexRoute
}

const SubjectsSubjectSlugRouteChildren: SubjectsSubjectSlugRouteChildren = {
  SubjectsSubjectSlugUnitSlugRoute: SubjectsSubjectSlugUnitSlugRoute,
  SubjectsSubjectSlugIndexRoute: SubjectsSubjectSlugIndexRoute,
}

const SubjectsSubjectSlugRouteWithChildren =
  SubjectsSubjectSlugRoute._addFileChildren(SubjectsSubjectSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  LearnSplatRoute: LearnSplatRoute,
  SubjectsSubjectSlugRoute: SubjectsSubjectSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
